<script>
  import { untrack } from 'svelte';
  import { normalizeFile, enqueueFile, playNow } from './channel-server.js';

  let { normEvents = [], onBumpersChange, connected = false, initialFolders = [] } = $props();

  let folders = $state([]);
  let folderFiles = $state({});
  let normStatus = $state({}); // path → 'pending'|'done'|'error'
  let queuedSet = $state(new Set());
  let bumperSet = $state(new Set());

  // Watch initialFolders reactively. Only `initialFolders` is tracked as a
  // dependency; everything else runs inside untrack() so reading/writing
  // `folders` never re-triggers the effect.
  $effect(() => {
    const incoming = initialFolders; // tracked — re-runs when prop changes
    if (!incoming?.length) return;
    untrack(() => {
      const newDirs = incoming.filter(d => !folders.includes(d));
      if (!newDirs.length) return;
      (async () => {
        for (const dir of newDirs) {
          folders = [...folders, dir];
          await scanFolder(dir);
        }
      })();
    });
  });

  const isTauri = '__TAURI_INTERNALS__' in window || '__TAURI__' in window;

  function toggleBumper(path) {
    const next = new Set(bumperSet);
    if (next.has(path)) next.delete(path);
    else next.add(path);
    bumperSet = next;
    onBumpersChange?.(Array.from(bumperSet));
  }

  async function addFolder() {
    if (isTauri) {
      const { open } = await import('@tauri-apps/plugin-dialog');
      const dir = await open({ directory: true, multiple: false });
      if (dir && !folders.includes(dir)) {
        folders = [...folders, dir];
        await scanFolder(dir);
      }
    } else {
      const dir = prompt('Enter folder path:');
      if (dir && !folders.includes(dir)) {
        folders = [...folders, dir];
        await scanFolder(dir);
      }
    }
  }

  let playNowError = $state(null);

  async function scanFolder(dir) {
    if (isTauri) {
      const { readDir } = await import('@tauri-apps/plugin-fs');
      try {
        const files = await collectFiles(readDir, dir);
        folderFiles = { ...folderFiles, [dir]: files };
      } catch (e) {
        console.error('scanFolder error', e);
      }
    }
  }

  async function collectFiles(readDir, dir, depth = 0) {
    if (depth > 4) return [];
    const entries = await readDir(dir);
    const results = [];
    for (const e of entries) {
      if (!e.name) continue;
      const fullPath = `${dir}/${e.name}`;
      if (e.isDirectory) {
        // Skip directories generated by the channel server
        if (['public', 'cache', 'node_modules', '.git'].includes(e.name)) continue;
        const sub = await collectFiles(readDir, fullPath, depth + 1);
        results.push(...sub);
      } else if (
        /\.(mp4|mkv|avi|mov|wmv|flv|ts|mp3|flac|aac|ogg|wav|m4a)$/i.test(e.name) &&
        !/^seg_\d+\.ts$/i.test(e.name) &&   // HLS segments
        !/\.norm\.ts$/i.test(e.name)          // transcoded cache files
      ) {
        results.push({ name: e.name, path: fullPath, status: 'ready' });
      }
    }
    return results;
  }

  async function normalize(path) {
    normStatus = { ...normStatus, [path]: 'pending' };
    await normalizeFile(path);
  }

  async function enqueue(path) {
    await enqueueFile(path);
    queuedSet = new Set([...queuedSet, path]);
  }

  async function handlePlayNow(path) {
    playNowError = null;
    try {
      await playNow(path);
    } catch (e) {
      playNowError = e.message;
      setTimeout(() => { playNowError = null; }, 4000);
    }
  }

  $effect(() => {
    const evts = normEvents; // tracked
    untrack(() => {
      const updates = {};
      for (const evt of evts) {
        if (evt.type === 'norm_done') updates[evt.file] = 'done';
        if (evt.type === 'norm_error') updates[evt.file] = 'error';
      }
      if (Object.keys(updates).length) {
        normStatus = { ...normStatus, ...updates };
      }
    });
  });
</script>

<div class="library">
  <div class="library-header">
    <strong>LIBRARY</strong>
    <button onclick={addFolder}>+ Add Folder</button>
  </div>
  {#if playNowError}
    <div class="play-error">{playNowError}</div>
  {/if}

  {#if folders.length === 0}
    <div class="empty">Add a media folder to get started</div>
  {:else}
    {#each folders as folder}
      <div class="folder">
        <div class="folder-name">
          <span>📁 {folder.split('/').pop()}</span>
          <button class="refresh-btn" onclick={() => scanFolder(folder)} title="Refresh folder">↺</button>
        </div>
        <div class="files">
          {#each (folderFiles[folder] ?? []) as file}
            <div class="file-row">
              <span class="file-name" title={file.path}>{file.name}</span>
              <span class="file-status">
                {#if normStatus[file.path] === 'pending'}
                  <span class="badge pending">transcoding…</span>
                {:else if normStatus[file.path] === 'done'}
                  <span class="badge ok" title="Transcoded and ready">✓</span>
                {:else if normStatus[file.path] === 'error'}
                  <span class="badge err" title="Transcode failed — check console">✗</span>
                {:else}
                  <button class="mini" onclick={() => normalize(file.path)} title="Pre-transcode for faster queuing">prep</button>
                {/if}
                <button
                  class="mini bump-btn"
                  class:bumper={bumperSet.has(file.path)}
                  onclick={() => toggleBumper(file.path)}
                  title={bumperSet.has(file.path) ? 'Remove bumper tag' : 'Tag as bumper'}
                >🎬</button>
                {#if connected}
                  <button
                    class="mini play-now"
                    onclick={() => handlePlayNow(file.path)}
                    title="Play this immediately (skips current)"
                  >▶ Now</button>
                {/if}
                <button
                  class="mini enqueue"
                  class:queued={queuedSet.has(file.path)}
                  onclick={() => enqueue(file.path)}
                  title="Add to end of queue"
                >+ Queue</button>
              </span>
            </div>
          {/each}
        </div>
      </div>
    {/each}
  {/if}
</div>

<style>
  .library {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
    font-family: monospace;
    font-size: 0.8rem;
  }

  .play-error {
    padding: 0.35rem 0.5rem;
    background: #1a0000;
    border-bottom: 1px solid #500;
    color: #f66;
    font-size: 0.72rem;
  }

  .library-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.5rem;
    border-bottom: 1px solid #222;
    color: #aaa;
  }

  .library-header button {
    background: #1a1a1a;
    border: 1px solid #333;
    color: #ccc;
    padding: 0.2rem 0.5rem;
    cursor: pointer;
    font-family: monospace;
    font-size: 0.75rem;
  }

  .empty {
    padding: 1rem 0.5rem;
    color: #444;
    font-size: 0.75rem;
  }

  .folder { margin: 0.5rem 0; }

  .folder-name {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.3rem 0.5rem;
    color: #888;
    font-size: 0.75rem;
    background: #0d0d0d;
  }

  .refresh-btn {
    background: none;
    border: none;
    color: #444;
    cursor: pointer;
    font-size: 0.85rem;
    padding: 0 0.2rem;
    line-height: 1;
  }
  .refresh-btn:hover { color: #aaa; }

  .files { overflow-y: auto; max-height: 300px; }

  .file-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.2rem 0.5rem;
    border-bottom: 1px solid #0d0d0d;
    gap: 0.5rem;
  }

  .file-row:hover { background: #111; }
  .file-row:hover .file-status { display: flex; }

  .file-name {
    flex: 1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    color: #ccc;
    min-width: 0;
  }

  .file-status {
    display: none;
    gap: 0.25rem;
    align-items: center;
    flex-shrink: 0;
  }

  .mini {
    background: #111;
    border: 1px solid #2a2a2a;
    color: #888;
    padding: 0.1rem 0.3rem;
    cursor: pointer;
    font-family: monospace;
    font-size: 0.7rem;
  }

  .enqueue { color: #4a9; border-color: #4a92; }
  .enqueue.queued { color: #2a6; border-color: #2a62; }

  .play-now { color: #fa4; border-color: #fa42; }
  .play-now:hover { background: #1a1200; color: #fc6; }

  .bump-btn { color: #555; border-color: #2a2a2a; font-size: 0.65rem; padding: 0.1rem 0.25rem; }
  .bump-btn.bumper { color: #fa4; border-color: #fa44; background: #1a1200; }

  .badge {
    font-size: 0.7rem;
    padding: 0.1rem 0.3rem;
  }
  .badge.pending { color: #aa0; }
  .badge.ok { color: #4a9; }
  .badge.err { color: #f44; }
</style>
